// Each new term in the fibonacci sequence is generated by adding the previous two terms.
// Find the sum of the even-valued-terms whose values do not exceed four million.

function GetFibValue() {

    let previous = 1;
    let current = 2;
    let sum = 1;

    while (current < 4000000) {
        sum += (current % 2 == 0) ? current : 0;
        let temp = previous + current;
        previous = current;
        current = temp;
    }

    return sum;
}

console.log(GetFibValue());
